Pre final branch
1khansaad/04-Ecommers-card-UI-project pull request #1
Opened 2022-01-11 14:53 UTC by 1khansaad

2022-01-11 20:10 UTC, Tauqeer-Ahmed-99 approved these changes
LGTM

2022-01-12 14:54 UTC, syedabdullahali approved these changes

2022-01-12 14:54 UTC, syedabdullahali commented on style.css
> +  margin-bottom: 5px;
use shorthand property

2022-01-13 08:51 UTC, nehalskdev requested changes
Make changes as suggested

2022-01-13 08:51 UTC, nehalskdev commented on style.css
> +  margin-bottom: 5px;
```suggestion
  margin: 0 0 5px 0;
```

2022-01-13 08:51 UTC, nehalskdev commented on style.css
> +  margin-top: 7px;
```suggestion
  margin: 7px 0 0 0;
```

2022-02-20 17:22 UTC, merged